Repository Oneflow-Inc/oneflow-documentation, pull requests merged in 2021-09, with the labels that each got.

#366 add labels check
  .github/workflows/pr.yml
Labels: enhancement

#368 resize by LiuNing
  cn/docs/basics/04_build_network.md
Labels: fix

#372 fix typos in ddp article
  cn/docs/code/parallelism/ddp_train.py
  cn/docs/parallelism/05_ddp.md
Labels: cn

#361 add 02 tensor
  cn/docs/basics/02_tensor.md
  en/docs/basics/02_tensor.md
  en/mkdocs.yml
Labels: en

#374 change flow in output into oneflow
  cn/docs/parallelism/03_consistent_tensor.md
Labels: cn

#360 Add 01 quickstart
  en/docs/basics/01_quickstart.md
  en/docs/basics/imgs/qq_group.png
  en/mkdocs.yml
Labels: en

#367 03_consistent_tensor translate by zhanghuihong guan
  cn/docs/basics/03_dataset_dataloader.md
  cn/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/imgs/boxing_s2b.png
  en/docs/parallelism/imgs/matmul_data_paralelism.png
  en/docs/parallelism/imgs/matmul_model_paralelism.png
  en/docs/parallelism/imgs/multi-matmul.png
  en/mkdocs.yml
Labels: en

#376 LiuNing en version
  en/docs/basics/04_build_network.md
  en/docs/basics/06_optimization.md
Labels: en

#369 Add 08 nn graph en
  en/docs/basics/08_nn_graph.md
  en/docs/basics/imgs/dynamic_graph.gif
  en/docs/basics/imgs/poly_fit.png
  en/docs/basics/imgs/static_graph.png
  en/mkdocs.yml
Labels: en

#370 add parallelism 01 & 02 en version
  en/docs/parallelism/01_introduction.md
  en/docs/parallelism/02_sbp.md
  en/docs/parallelism/imgs/consistent-view.png
  en/docs/parallelism/imgs/gpt3-overview.png
  en/docs/parallelism/imgs/matmul_logical.png
  en/docs/parallelism/imgs/realy.png
  en/docs/parallelism/imgs/sbp-example.png
  en/mkdocs.yml
Labels: en

#377 add 06_pipeline.md
  en/docs/parallelism/06_pipeline.md
Labels: en

#375 General Review on English Docs
  cn/docs/parallelism/03_consistent_tensor.md
  en/docs/basics/01_quickstart.md
  en/docs/basics/02_tensor.md
  en/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/06_pipeline.md
Labels: en

#378 minor fix
  cn/docs/parallelism/01_introduction.md
  cn/docs/parallelism/04_launch.md
Labels: cn

#379 fix python code in 06 pipeline
  en/docs/parallelism/06_pipeline.md
Labels: en

#380 update run-mike.sh for v0.5.0
  scripts/run-mike.sh
Labels: enhancement, cn, en

#381 fix typos in sbp image
  cn/docs/parallelism/imgs/sbp-example.png
  en/docs/parallelism/imgs/sbp-example.png
Labels: cn, en

#383 Update 08_nn_graph.md
  cn/docs/basics/08_nn_graph.md
Labels: cn

#382 fix quickstart
  cn/docs/basics/01_quickstart.md
  cn/docs/basics/03_dataset_dataloader.md
  en/docs/basics/01_quickstart.md
  en/docs/basics/03_dataset_dataloader.md
Labels: cn, en
