Repository Oneflow-Inc/oneflow-documentation, pull requests merged in 2022-07, with the labels that each got.

#496 change API web site
  cn/mkdocs.yml
Labels: cn

#495 Refine "Global Tensor 参与计算" 和 ”扩展阅读“ 部分
  cn/docs/cookies/global_tensor.md
Labels: cn

#500 redirects global_tensor to consistent_tensor
  cn/mkdocs.yml
  en/mkdocs.yml
  requirements.txt
Labels: enhancement, cn, en, ci

#494 Refine "使用 Global Tensor 进行多机多设备编程"
  cn/docs/cookies/global_tensor.md
  cn/mkdocs.yml
Labels: cn

#493 How to Global
  cn/docs/cookies/global_tensor.md
  cn/mkdocs.yml
Labels: cn, ci

#503 update DistributedDataParallel url
  cn/docs/parallelism/05_ddp.md
Labels: cn

#506 refine bug about v0.8.1
  cn/docs/assets/install-selector.js
  en/docs/assets/install-selector.js
Labels: cn, en, fix

#505 Update doc of graph api
  cn/docs/cookies/zero.md
  cn/docs/parallelism/06_pipeline.md
  en/docs/cookies/zero.md
  en/docs/parallelism/06_pipeline.md
Labels: enhancement, cn, en

#507 refine API
  cn/docs/basics/01_quickstart.md
  cn/docs/basics/02_tensor.md
  cn/docs/basics/03_dataset_dataloader.md
  cn/docs/basics/04_build_network.md
  cn/docs/basics/05_autograd.md
  cn/docs/basics/06_optimization.md
  cn/docs/basics/07_model_load_save.md
  cn/docs/basics/08_nn_graph.md
  cn/docs/cookies/global_tensor.md
  cn/docs/cookies/one_embedding.md
  cn/docs/cookies/zero.md
  cn/docs/parallelism/03_consistent_tensor.md
  cn/docs/parallelism/04_2d-sbp.md
  cn/docs/parallelism/05_ddp.md
  cn/docs/parallelism/06_pipeline.md
  en/docs/basics/01_quickstart.md
  en/docs/basics/02_tensor.md
  en/docs/basics/03_dataset_dataloader.md
  en/docs/basics/04_build_network.md
  en/docs/basics/05_autograd.md
  en/docs/basics/06_optimization.md
  en/docs/basics/07_model_load_save.md
  en/docs/basics/08_nn_graph.md
  en/docs/cookies/global_tensor.md
  en/docs/cookies/one_embedding.md
  en/docs/cookies/zero.md
  en/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/04_2d-sbp.md
  en/docs/parallelism/05_ddp.md
  en/docs/parallelism/06_pipeline.md
Labels: enhancement, cn, en, ci

#509 update api urls
  cn/docs/cookies/activation_checkpointing.md
  cn/docs/cookies/amp.md
  en/docs/basics/02_tensor.md
  en/docs/cookies/activation_checkpointing.md
  en/docs/cookies/amp.md
Labels: cn, en, fix

#510 add tag for v0.8.0
  scripts/run-mike.sh
Labels: cn, en, ci
