Repository Oneflow-Inc/oneflow-documentation, pull requests merged in 2022-04, with the labels that each got.

#458 torch2flow
  cn/docs/cookies/torch2flow.md
  cn/mkdocs.yml
  en/docs/cookies/torch2flow.md
  en/mkdocs.yml
Labels: cn, en

#460 fix typos
  en/docs/cookies/oneflow2onnnx.md
Labels: en

#451 Add AMP & Activation Checkpointing Tutorials
  cn/docs/cookies/activation_checkpointing.md
  cn/docs/cookies/amp.md
  cn/mkdocs.yml
  en/docs/cookies/activation_checkpointing.md
  en/docs/cookies/amp.md
  en/mkdocs.yml
Labels: enhancement, cn, en

#464 update article by chenqiaoling
  cn/docs/cookies/one_embedding.md
  cn/mkdocs.yml
  en/docs/cookies/one_embedding.md
Labels: cn, en

#466 fix oneEmbedding
  cn/docs/cookies/one_embedding.md
  en/mkdocs.yml
Labels: cn, en, fix

#472 Update requirements.txt
  requirements.txt
Labels: fix

#475 fix typos
  cn/docs/parallelism/02_sbp.md
  en/docs/parallelism/02_sbp.md
Labels: cn, en, fix

#476 fix a typo
  en/docs/parallelism/02_sbp.md
Labels: en, fix

#462 Add Transfer Learning Tutorial
  cn/docs/cookies/transfer_learning.md
  cn/mkdocs.yml
  en/docs/cookies/transfer_learning.md
  en/mkdocs.yml
Labels: enhancement, cn, en

#467 Add ZeRO Tutorial
  cn/docs/cookies/imgs/Three_Stages_of_ZeRO-DP_Optimizations.jpg
  cn/docs/cookies/zero.md
  cn/mkdocs.yml
  en/docs/cookies/imgs/Three_Stages_of_ZeRO-DP_Optimizations.jpg
  en/docs/cookies/zero.md
  en/mkdocs.yml
Labels: enhancement, cn, en

#459 fix some code in 08_nn_graph.md
  cn/docs/basics/08_nn_graph.md
Labels: fix

#479 修复 nn_graph_code 英文文档中的错误。
  cn/docs/basics/08_nn_graph.md
  en/docs/basics/08_nn_graph.md
Labels: fix

#484 Fix Code Error in Transfer Learning Tutorial
  cn/docs/cookies/transfer_learning.md
  en/docs/cookies/transfer_learning.md
Labels: cn, en, fix
