Repository Oneflow-Inc/oneflow-documentation, pull requests merged in 2022-03, with the labels that each got.

#429 add documents_en for serving
  en/docs/basics/08_nn_graph.md
  en/docs/cookies/imgs/oneflow-serving-demo.png
  en/docs/cookies/imgs/triton-oneflow-backend.png
  en/docs/cookies/serving.md
  en/mkdocs.yml
Labels: en

#420 翻译sbp和ddp
  en/docs/parallelism/01_introduction.md
  en/docs/parallelism/02_sbp.md
  en/docs/parallelism/05_ddp.md
Labels: enhancement, en

#436 fix some typos
  cn/docs/parallelism/04_launch.md
  cn/docs/parallelism/05_ddp.md
  en/docs/parallelism/04_launch.md
Labels: fix

#438 更新 Tutorial 中 graph 的 save & load
  cn/docs/basics/08_nn_graph.md
  en/docs/basics/08_nn_graph.md
Labels: cn, en

#435 添加英文版的 ONNX 文章
  en/docs/cookies/imgs/cat.jpg
  en/docs/cookies/oneflow2onnnx.md
  en/mkdocs.yml
Labels: en

#439 fix 04_2d-sbp.md
  cn/docs/parallelism/04_2d-sbp.md
Labels: cn, fix

#441 Trans 2dsbp
  cn/docs/parallelism/04_2d-sbp.md
  en/docs/parallelism/02_sbp.md
  en/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/04_2d-sbp.md
  en/docs/parallelism/imgs/2d-sbp.png
  en/mkdocs.yml
Labels: en

#442 release v0.7.0
  scripts/run-mike.sh
Labels: cn, en, release

#446 Update serving.md
  cn/docs/cookies/serving.md
  en/docs/cookies/serving.md
Labels: cn, en, fix

#452 Update 02_sbp.md fix typos
  cn/docs/parallelism/02_sbp.md
Labels: cn, fix

#445 Add 2D SDP Example
  cn/docs/parallelism/04_2d-sbp.md
  en/docs/parallelism/04_2d-sbp.md
Labels: enhancement, cn, en

#456 update sbp pictures
  cn/docs/parallelism/imgs/sbp-example.png
  en/docs/parallelism/imgs/sbp-example.png
Labels: cn, en, fix
