Repository Oneflow-Inc/oneflow-documentation, pull requests merged in 2022-05, with the labels that each got.

#468 add CI for markdown files
  .gitignore
  cn/docs/basics/05_autograd.md
  cn/docs/basics/08_nn_graph.md
  en/docs/basics/02_tensor.md
  en/docs/basics/03_dataset_dataloader.md
  en/docs/basics/05_autograd.md
  en/docs/basics/08_nn_graph.md
  requirements.txt
  scripts/markdown_ci/README.md
  scripts/markdown_ci/__init__.py
  scripts/markdown_ci/configs/basics_01_quick_start.yml
  scripts/markdown_ci/configs/basics_02_tensor.yml
  scripts/markdown_ci/configs/basics_03_dataset.yml
  scripts/markdown_ci/configs/basics_04_build_network.yml
  scripts/markdown_ci/configs/basics_05_autograd.yml
  scripts/markdown_ci/configs/basics_06_optimization.yml
  scripts/markdown_ci/configs/basics_07_save_load.yml
  scripts/markdown_ci/configs/basics_08_nn_graph.yml
  scripts/markdown_ci/extract_code_block.py
  scripts/markdown_ci/run_by_yamls.py
  scripts/markdown_ci/run_markdown_codes.py
  scripts/run-markdown-ci.sh
Labels: enhancement, cn, en

#486 fix typos
  cn/docs/cookies/serving.md
  en/docs/cookies/serving.md
Labels: cn, en, fix

#487 update requirements
  requirements.txt
Labels: enhancement

#488 add markdown ci
  .github/workflows/markdown-ci.yml
Labels: enhancement

#485 Add autotest for guide section
  .github/workflows/markdown-ci.yml
  cn/docs/cookies/oneflow2onnnx.md
  cn/docs/cookies/torch2flow.md
  cn/docs/cookies/transfer_learning.md
  en/docs/cookies/oneflow2onnnx.md
  en/docs/cookies/torch2flow.md
  en/docs/cookies/transfer_learning.md
  requirements.txt
  scripts/ci-requirements.txt
  scripts/markdown_ci/configs/guide_activation_checkpointing.yml
  scripts/markdown_ci/configs/guide_amp.yml
  scripts/markdown_ci/configs/guide_one_embedding.yml
  scripts/markdown_ci/configs/guide_oneflow2onnx.yml
  scripts/markdown_ci/configs/guide_torch2flow.yml
  scripts/markdown_ci/configs/guide_transfer_learning.yml
  scripts/markdown_ci/configs/guide_zero.yml
  scripts/markdown_ci/run_by_yamls.py
  scripts/run-markdown-ci.sh
Labels: enhancement, cn, en, ci

#489 add .oneflow cache
  .github/workflows/markdown-ci.yml
Labels: enhancement, ci
