Repository Oneflow-Inc/oneflow-documentation, pull requests merged in 2022-02, with the labels that each got.

#408 为文档首页添加pip安装命令的选择面板
  cn/docs/assets/index-mdx.css
  cn/docs/assets/install-selector.css
  cn/docs/assets/install-selector.js
  cn/overrides/templates/home.html
  en/docs/assets/index-mdx.css
  en/docs/assets/install-selector.css
  en/docs/assets/install-selector.js
  en/overrides/templates/home.html
Labels: enhancement, cn, en

#410 Fix en install hint
  en/overrides/templates/home.html
Labels: en, fix

#412 安装命令选择面板支持复制
  cn/docs/assets/install-selector.css
  cn/docs/assets/install-selector.js
  cn/overrides/templates/home.html
  en/docs/assets/install-selector.css
  en/docs/assets/install-selector.js
  en/overrides/templates/home.html
Labels: cn, en

#413 fix en typos in global tensor article
  en/docs/parallelism/03_consistent_tensor.md
Labels: en, fix

#415 Update articles with placement API changing
  cn/docs/parallelism/02_sbp.md
  cn/docs/parallelism/03_consistent_tensor.md
  cn/docs/parallelism/05_ddp.md
  cn/docs/parallelism/06_pipeline.md
  en/docs/parallelism/02_sbp.md
  en/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/06_pipeline.md
Labels: cn, en

#411 update: replace "consistent" with "global"
  cn/docs/basics/02_tensor.md
  cn/docs/parallelism/02_sbp.md
  cn/docs/parallelism/03_consistent_tensor.md
  cn/docs/parallelism/04_launch.md
  cn/docs/parallelism/05_ddp.md
  cn/docs/parallelism/06_pipeline.md
  cn/mkdocs.yml
  en/docs/basics/02_tensor.md
  en/docs/parallelism/02_sbp.md
  en/docs/parallelism/03_consistent_tensor.md
  en/docs/parallelism/04_launch.md
  en/docs/parallelism/06_pipeline.md
  en/mkdocs.yml
Labels: cn, en

#421 fix typos in cn/02_sbp.md
  cn/docs/parallelism/02_sbp.md
Labels: cn, fix

#416 Add graph debug doc
  cn/docs/basics/08_nn_graph.md
Labels: cn

#422 Transfer to flowvision
  cn/docs/basics/01_quickstart.md
  cn/docs/basics/03_dataset_dataloader.md
  en/docs/basics/01_quickstart.md
  en/docs/basics/03_dataset_dataloader.md
Labels: cn, en, fix

#403 add tutorial about 2d sbp
  cn/docs/parallelism/04_2d-sbp.md
  cn/docs/parallelism/imgs/2d-sbp.png
Labels: cn

#426 fix cn/mkdocs.yml
  cn/mkdocs.yml
Labels: cn

#427 Update 04_2d-sbp.md
  cn/docs/parallelism/04_2d-sbp.md
Labels: cn, fix

#406 add documents for serving
  cn/docs/basics/08_nn_graph.md
  cn/docs/cookies/imgs/oneflow-serving-demo.png
  cn/docs/cookies/imgs/triton-oneflow-backend.png
  cn/docs/cookies/serving.md
  cn/mkdocs.yml
Labels: cn

#425 Add_graph_debug_en
  en/docs/basics/08_nn_graph.md
Labels: en

#432 Update serving link
  cn/docs/cookies/serving.md
Labels: cn, fix

#430 Add oneflow2onnx (CN)
  cn/docs/cookies/imgs/cat.jpg
  cn/docs/cookies/oneflow2onnnx.md
  cn/mkdocs.yml
Labels: enhancement, cn
